login:
  url:
    path: /users/login

api-albums:
  url: http://albums-ws/users/%s/albums
  exception:
    not-found: Users albums are not found :(

jwt:
  token:
    expiration:
      time.ms: 764000000 #10 days
    secret: '{cipher}AQB6djI/PfxF62+eX9l0TxfluWq3KNy+jIK6eYSo6QhJHnBLHAD4XjJz+KA5/69chD28Fe53rERmjk0Rv+IQGwWzboD5ZlV2K9Ti/LIPHdilklkFV4viRDGehD39GYfpv0hbtWojuVW+hylwFDtZIUgWSUgATU8C0GcwgbqAORQJN/M2C2v0L18x1bk8ysrcJMIzQM0TovXv6EMhrr2T/hEkKDoIF3eyxyMgAxbZmG8bNcjcPrFfsD9O7Np0SGacbCUR+wlMFZPiHJCxa1aYXTGRjQpxs/tqMcOHAmFgJ+mbMjGZV28iJNXcsDfLJarJ+WdknxRnmYjUAA19lJhreR20FTiZorcYk1yus/mr7z6VfkeGbOLzAP2HwCiFCNCY65A='

eureka:
  password: '{cipher}AQB0NxFBgQTkd+OMAdXhyqA0wiPrUgB3ZhoiDwMmo//X6jcuwA7vUdBpOW7BWjDKmkzZRMl0XEXQM1mO2rKG1B1OmqMJJz1H/anqrue849uFL3c7C84JuYLTjyd4ON2jH5lwTnI1G9636oi92kwzCqpyXWcBXW8fTiR6nEkMyZ7zMBfZ4Opuz/05i+bw8mapjxiUxrPtJBG6DJRrXeRACuLgc66k5zzYildtv9/MwG7u013TxICs2xFjnoPuo4BlQNcyGFCMbPIK1ArjJ9+YZN4cK8yUNQYyKLwMbuh+ras5scoC7tAy7cgRvECQJd5sJmmcgfO7IoR6dAt1XGLuidj717yGu6X9kR+wTh7PiZ8vm6+X90NgIWWpy1C1dU+ucdg='
  client:
    service-url:
      defaultZone: http://robot:${eureka.password}@localhost:8010/eureka
